name: AWS Deploy dynamoDB Stream

on:
  pull_request:
    branches: [master]
    paths:
      - 'dynamoDBStreamFunction/*'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Change directory, install dependencies, and zip
        run: cd ./dynamoDBStreamFunction && npm install && zip -r ../deploy.zip .

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ secrets.AWS__LAMBDA_DDBSTREAM }}
          zip_file: deploy.zip
